# Generated by Django 3.2 on 2023-06-07 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_loggeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggeduser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loggeduser',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loggeduser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
