# Generated by Django 3.2 on 2023-05-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20230328_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='top_comment_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
