# Generated by Django 3.2 on 2023-02-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
