# Generated by Django 3.2 on 2023-05-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_read_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='entity_id',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='notification',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('POST_LIKE', 'POST_LIKE'), ('POST_COMMENT', 'POST_COMMENT'), ('POST_COMMENT_LIKE', 'POST_COMMENT_LIKE'), ('POST_COMMENT_REPLY', 'POST_COMMENT_REPLY'), ('POST_COMMENT_REPLY_LIKE', 'POST_COMMENT_REPLY_LIKE'), ('USER_FOLLOW', 'USER_FOLLOW'), ('STORY_LIKE', 'STORY_LIKE'), ('STORY_REPLY', 'STORY_REPLY')], max_length=50, null=True),
        ),
    ]
