# Generated by Django 3.2 on 2023-05-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_remove_notification_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='entity_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
