# Generated by Django 3.2 on 2023-06-04 16:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20230604_0000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participant',
            new_name='InboxParticipant',
        ),
    ]
