# Generated by Django 3.2 on 2023-06-04 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_participant_inboxparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxparticipant',
            name='inbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_participants', to='chat.inbox'),
        ),
    ]
