# Generated by Django 3.2 on 2023-06-04 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_alter_inboxparticipant_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='inbox_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='InboxParticipant',
        ),
    ]
