# Generated by Django 3.2 on 2023-06-04 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_auto_20230605_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user_inboxes', to=settings.AUTH_USER_MODEL),
        ),
    ]
