# Generated by Django 3.2 on 2023-06-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_read_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(blank=True, choices=[('TEXT', 'TEXT'), ('EMOJI', 'EMOJI')], max_length=20, null=True),
        ),
    ]
