# Generated by Django 3.2 on 2023-02-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20230220_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'stories'},
        ),
    ]
