# Generated by Django 3.2 on 2023-02-20 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0003_alter_story_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='view_status',
        ),
        migrations.AddField(
            model_name='story',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='story_viewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
