# Generated by Django 3.2 on 2023-02-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20230220_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
