# Generated by Django 3.2 on 2023-03-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_story_caption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'stories'},
        ),
        migrations.AlterField(
            model_name='story',
            name='caption',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
