# Generated by Django 3.2 on 2023-04-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_highlight_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
